// SPDX-FileCopyrightText: 2025 Dirius77
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Job;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DEN.Lobby.UI.Controls;

/// <summary>
///     A selection of job titles for this job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlternateTitleSelectionMenu : FancyWindow
{
    public event Action<(LocId, string)?>? OnSelectedAlternateTitleChanged;

    public AlternateTitleSelectionMenu(JobPrototype job,
        List<(LocId, string)> titles,
        string? selectedAlternateTitle = null)
    {
        RobustXamlLoader.Load(this);

        var selector = new RadioOptions<string>(RadioOptionsLayout.Vertical);
        var buttons = new List<(LocId, string)> { (job.ID, job.LocalizedName) };
        buttons.AddRange(titles);

        foreach (var titleData in buttons)
        {
            var title = GetButtonText(job, titleData.Item1, titleData.Item2);
            selector.AddItem(title, titleData.Item1, _ => OnSelectedAlternateTitleChanged?.Invoke(titleData));

            if (selectedAlternateTitle != null && titleData.Item1 == selectedAlternateTitle)
                selector.SelectByValue(titleData.Item1);
        }

        TitlesContainer.AddChild(selector);
        Titles.InvalidateMeasure();
    }

    private string GetButtonText(JobPrototype job, LocId id, string text) =>
        id == job.ID ? job.LocalizedName : text;

}
