// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Client.Message;
using Content.Shared._DEN.Hub;
using Content.Shared.CCVar;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;


namespace Content.Client._DEN.Hub;

/// <summary>
///     A selection of job titles for this job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HubPanel : PanelContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    [Dependency] private readonly IGameController _gameController = null!;
    [Dependency] private readonly ILogManager _logManager = null!;

    private const string HttpsString = "https://";

    private readonly ISawmill _sawmill;
    private HubSystem _hubSystem = null!;
    private string _serverId;

    public HubPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("hub-panel");

        var title = Loc.GetString("hub-panel-title");
        TitleLabel.SetMarkupPermissive(title);

        _serverId = _cfg.GetCVar(CCVars.ServerId);
        _cfg.OnValueChanged(CCVars.ServerId, OnServerIdChanged, true);

        _systemManager.SystemLoaded += OnSystemLoaded;
    }

    private void OnServerIdChanged(string serverId)
    {
        _serverId = serverId;
    }

    private void OnSystemLoaded(object? sender, SystemChangedArgs args)
    {
        if (args.System is not HubSystem hubSystem)
            return;

        _hubSystem = hubSystem;
        _hubSystem.OnHubServersUpdated += OnRefresh;
        _systemManager.SystemLoaded -= OnSystemLoaded;
    }

    private void OnRefresh(HubServersUpdatedEvent ev)
    {
        var servers = ev.Servers.Values.ToList();
        SetupEntries(servers);
    }

    private void SetupEntries(List<HubServer> serversUnsorted)
    {
        var name = HubPanelUtils.CreateColumnCategory("hub-panel-column-category-server-name");
        var status = HubPanelUtils.CreateColumnCategory("hub-panel-column-category-status");
        var playerCount = HubPanelUtils.CreateColumnCategory("hub-panel-column-category-player-count");
        var connect = HubPanelUtils.CreateColumnCategory("hub-panel-column-category-connect");

        ServersGrid.RemoveAllChildren();

        ServersGrid.AddChild(name);
        ServersGrid.AddChild(status);
        ServersGrid.AddChild(playerCount);
        ServersGrid.AddChild(connect);

        var servers = serversUnsorted.OrderByDescending(server => server.ServerId).ToList();

        if (servers.Count == 0)
            Visible = false;

        foreach (var server in servers)
        {
            var connectFriendly = GetConnectFriendlyAddress(server.ConnectAddress);

            var titleLabel = HubPanelUtils.SetupTitleLabel(server);
            var statusLabel = HubPanelUtils.SetupStatusLabel(server);
            var playersLabel = HubPanelUtils.SetupPlayersLabel(server);
            var connectButton = HubPanelUtils.SetupConnectButton(server, _serverId, connectFriendly);
            connectButton.OnPressed += _ => TryConnect(connectFriendly);

            ServersGrid.AddChild(titleLabel);
            ServersGrid.AddChild(statusLabel);
            ServersGrid.AddChild(playersLabel);
            ServersGrid.AddChild(connectButton);
        }
    }

    private string GetConnectFriendlyAddress(string formerAddress)
    {
        int startPos;

        // it's either https:// or http://. this is enforced.
        // ReSharper disable once ConvertIfStatementToConditionalTernaryExpression ugly
        if (formerAddress.StartsWith(HttpsString))
            startPos = HttpsString.Length;
        else
            startPos = HttpsString.Length - 1;

        var newAddress = formerAddress.Substring(startPos);

        if (!newAddress.Contains("://"))
        {
            newAddress = "udp://" + newAddress;
        }
        
        return newAddress;
    }

    private void TryConnect(string connectAddress)
    {
        try
        {
            _gameController.Redial(connectAddress);
        }
        catch (Exception ex)
        {
            _sawmill.Error($"{ex}");
        }
    }
}
